import localFont from "next/font/local";
import "./globals.css";

// fuentes 
const openSansBold = localFont({
  src: "./fonts/OpenSans-Bold.ttf",
  variable: "--font-open-sans-bold",
  weight: "700", 
});

const penSansExtraBold = localFont({
  src: "./fonts/OpenSans-ExtraBold.ttf",
  variable: "--font-pen-sans-extrabold",
  weight: "800",  
});

const penSansSemiBold = localFont({
  src: "./fonts/OpenSans-SemiBold.ttf",
  variable: "--font-pen-sans-semibold",
  weight: "600",  
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${openSansBold.variable} ${penSansExtraBold.variable} ${penSansSemiBold.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}